### ISSUE TITLE
Nefunguje

### ISSUE THREAD

**Issue by sleduj-tv** [cvb941/magiogo-iptv-server#23]
Ahoj, ked chcem spustit tvoj script, mam nastavene username aj vsetko, vypise mi tento error:
Stream quality configured to: HIGH (p4)
Logging in to Magio Go TV
Traceback (most recent call last):
  File "/usr/local/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/flask/cli.py", line 1063, in main
    cli.main()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask/cli.py", line 911, in run_command
    raise e from None
  File "/usr/local/lib/python3.8/dist-packages/flask/cli.py", line 897, in run_command
    app = info.load_app()
  File "/usr/local/lib/python3.8/dist-packages/flask/cli.py", line 312, in load_app
    app = locate_app(import_name, None, raise_if_not_found=False)
  File "/usr/local/lib/python3.8/dist-packages/flask/cli.py", line 218, in locate_app
    __import__(module_name)
  File "/root/magiogo-iptv-server/app.py", line 128, in <module>
    refresh()
  File "/root/magiogo-iptv-server/app.py", line 106, in refresh
    channels = magio.channels()
  File "/root/magiogo-iptv-server/magiogo.py", line 140, in channels
    self._login()
  File "/root/magiogo-iptv-server/magiogo.py", line 130, in _login
    self._post('https://skgo.magio.tv/v2/auth/login',
  File "/root/magiogo-iptv-server/magiogo.py", line 107, in _post
    self._check_response(resp)
  File "/root/magiogo-iptv-server/magiogo.py", line 82, in _check_response
    raise MagioGoException(resp['errorCode'], resp['errorMessage'])
magiogo.MagioGoException: ('Bad Request', 'Nastala chyba. Označenie chyby: 1QLWWBJ')
root@Kubain:~/magiogo-iptv-server# python3 app.py
Stream quality configured to: HIGH (p4)
Logging in to Magio Go TV
Traceback (most recent call last):
  File "app.py", line 128, in <module>
    refresh()
  File "app.py", line 106, in refresh
    channels = magio.channels()
  File "/root/magiogo-iptv-server/magiogo.py", line 140, in channels
    self._login()
  File "/root/magiogo-iptv-server/magiogo.py", line 130, in _login
    self._post('https://skgo.magio.tv/v2/auth/login',
  File "/root/magiogo-iptv-server/magiogo.py", line 107, in _post
    self._check_response(resp)
  File "/root/magiogo-iptv-server/magiogo.py", line 82, in _check_response
    raise MagioGoException(resp['errorCode'], resp['errorMessage'])
magiogo.MagioGoException: ('Bad Request', 'Nastala chyba. Označenie chyby: teDVBkK')
Nevies to opravit? Dik

**Comment by cvb941** [comment]
Ahoj, skusal som pustit skript dnes a tuto chybu mi pise ked nemam nastavene environment variables. Si si isty ze ich nastavujes dobre? Podla https://github.com/cvb941/magiogo-iptv-server?tab=readme-ov-file#python

**Comment by sleduj-tv** [comment]
Ahoj, vsetko som nastavil podla navodu neboj, skusim to znova a poslem ti vysledok

**Comment by sleduj-tv** [comment]
Opat rovnaky vypis:
Stream quality configured to: HIGH (p4)
Logging in to Magio Go TV
Traceback (most recent call last):
  File "/usr/local/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/flask/cli.py", line 1063, in main
    cli.main()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask/cli.py", line 911, in run_command
    raise e from None
  File "/usr/local/lib/python3.8/dist-packages/flask/cli.py", line 897, in run_command
    app = info.load_app()
  File "/usr/local/lib/python3.8/dist-packages/flask/cli.py", line 312, in load_app
    app = locate_app(import_name, None, raise_if_not_found=False)
  File "/usr/local/lib/python3.8/dist-packages/flask/cli.py", line 218, in locate_app
    __import__(module_name)
  File "/root/magiogo-iptv-server/app.py", line 128, in <module>
    refresh()
  File "/root/magiogo-iptv-server/app.py", line 106, in refresh
    channels = magio.channels()
  File "/root/magiogo-iptv-server/magiogo.py", line 140, in channels
    self._login()
  File "/root/magiogo-iptv-server/magiogo.py", line 130, in _login
    self._post('https://skgo.magio.tv/v2/auth/login',
  File "/root/magiogo-iptv-server/magiogo.py", line 107, in _post
    self._check_response(resp)
  File "/root/magiogo-iptv-server/magiogo.py", line 82, in _check_response
    raise MagioGoException(resp['errorCode'], resp['errorMessage'])
magiogo.MagioGoException: ('Bad Request', 'Nastala chyba. Označenie chyby: jIicNxq')
Preinstaloval som to a stale to nejde

**Comment by cvb941** [comment]
Hmm tak skus si to asi zdebugovat niekde a pozriet co je problem, u mna ma to prihlasuje ¯\_(ツ)_/¯

**Comment by sleduj-tv** [comment]
skusil si to dnes? stale erroruje

**Comment by cvb941** [comment]
Včera aj dnes, prihlásilo ma. Keď som dal zlé údaje hodilo mi iný error. Neviem ti takto pomôcť na diaľku asi, musíš si to sám vykrokovať v kóde a pozrieť, čo sa deje.

**Comment by sleduj-tv** [comment]
ci vravim ze mi to nejde. udaje som dal ale furt nejde. ked chatgpt to napravil tak to zas nedavalo zoznam, chyba musi byt v kode

**Comment by sveco86** [comment]
Malo by byt opravene v #25
