### ISSUE TITLE
Still does not work

### ISSUE THREAD

**Issue by Gouster4** [cvb941/magiogo-iptv-server#9]
Stream quality configured to: HIGH (p4)
Logging in to Magio Go TV
Traceback (most recent call last):
  File "/usr/local/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 995, in main
    cli.main(args=sys.argv[1:])
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 601, in main
    return super().main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 850, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 325, in __init__
    self._load_unlocked()
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 351, in _load_unlocked
    self._app = rv = self.loader()
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 411, in load_app
    app = locate_app(self, import_name, None, raise_if_not_found=False)
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 260, in locate_app
    __import__(module_name)
  File "/srv/system/magiogo-iptv-server/app.py", line 128, in <module>
    refresh()
  File "/srv/system/magiogo-iptv-server/app.py", line 106, in refresh
    channels = magio.channels()
  File "/srv/system/magiogo-iptv-server/magiogo.py", line 142, in channels
    self._login()
  File "/srv/system/magiogo-iptv-server/magiogo.py", line 132, in _login
    self._post('https://skgo.magio.tv/v2/auth/login',
  File "/srv/system/magiogo-iptv-server/magiogo.py", line 107, in _post
    self._check_response(resp)
  File "/srv/system/magiogo-iptv-server/magiogo.py", line 82, in _check_response
    raise MagioGoException(resp['errorCode'], resp['errorMessage'])
magiogo.MagioGoException: ('Bad Request', 'Nastala chyba. Označenie chyby: PAFqVYZ')

**Comment by cvb941** [comment]
Are you running on Docker or Python?

If Python, have you upgraded the pip dependencies from requirements.txt?

**Comment by Gouster4** [comment]
> Are you running on Docker or Python?
> 
> If Python, have you upgraded the pip dependencies from requirements.txt?

Im running it on Python, and in my launch script i have included "pip install -r requirements.txt" at beginning of .sh script.

cat magio.sh
cd magiogo-iptv-server
pip install -r requirements.txt
set MAGIO_USERNAME=******
set MAGIO_PASSWORD=*******
set MAGIO_SERVER_PUBLIC_URL=http://127.0.0.1:5000
set MAGIO_GUIDE_DAYS=7
set MAGIO_GUIDE_REFRESH_HOURS=12
set MAGIO_QUALITY=HIGH
flask run --host=0.0.0.0

**Comment by Gouster4** [comment]
sh magio.sh
Collecting python_xmltv
  Cloning https://github.com/mforkel/python-xmltv.git to /tmp/pip-install-045b3mur/python-xmltv_8fc1a4e686e34e7a8afb8ef6bcb1090c
  Running command git clone --filter=blob:none --quiet https://github.com/mforkel/python-xmltv.git /tmp/pip-install-045b3mur/python-xmltv_8fc1a4e686e34e7a8afb8ef6bcb1090c
  Resolved https://github.com/mforkel/python-xmltv.git to commit 878ee821d036ffb682b7598ac666cbf244cdfa5e
  Preparing metadata (setup.py) ... done
Requirement already satisfied: APScheduler==3.8.1 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (3.8.1)
Requirement already satisfied: Flask==2.0.3 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 2)) (2.0.3)
Requirement already satisfied: Jinja2==3.0.3 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 3)) (3.0.3)
Requirement already satisfied: pytz==2021.3 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 4)) (2021.3)
Requirement already satisfied: roman==3.3 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 5)) (3.3)
Requirement already satisfied: six==1.16.0 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 6)) (1.16.0)
Requirement already satisfied: tzlocal<3.0 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 7)) (2.1)
Requirement already satisfied: urllib3==1.26.8 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 8)) (1.26.8)
Requirement already satisfied: requests==2.27.1 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 9)) (2.27.1)
Requirement already satisfied: pip==22.0.3 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 10)) (22.0.3)
Requirement already satisfied: MarkupSafe==2.0.1 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 11)) (2.0.1)
Requirement already satisfied: Werkzeug==2.0.3 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 12)) (2.0.3)
Requirement already satisfied: click==8.0.3 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 13)) (8.0.3)
Requirement already satisfied: itsdangerous==2.0.1 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 14)) (2.0.1)
Requirement already satisfied: certifi==2021.10.8 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 15)) (2021.10.8)
Requirement already satisfied: chardet==4.0.0 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 16)) (4.0.0)
Requirement already satisfied: idna==3.3 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 17)) (3.3)
Requirement already satisfied: setuptools==60.9.2 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 18)) (60.9.2)
Requirement already satisfied: zipp==3.7.0 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 19)) (3.7.0)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.8/site-packages (from requests==2.27.1->-r requirements.txt (line 9)) (2.0.12)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Stream quality configured to: HIGH (p4)
Logging in to Magio Go TV
Traceback (most recent call last):
  File "/usr/local/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 995, in main
    cli.main(args=sys.argv[1:])
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 601, in main
    return super().main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 850, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 325, in __init__
    self._load_unlocked()
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 351, in _load_unlocked
    self._app = rv = self.loader()
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 411, in load_app
    app = locate_app(self, import_name, None, raise_if_not_found=False)
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 260, in locate_app
    __import__(module_name)
  File "/srv/system/magiogo-iptv-server/app.py", line 128, in <module>
    refresh()
  File "/srv/system/magiogo-iptv-server/app.py", line 106, in refresh
    channels = magio.channels()
  File "/srv/system/magiogo-iptv-server/magiogo.py", line 140, in channels
    self._login()
  File "/srv/system/magiogo-iptv-server/magiogo.py", line 130, in _login
    self._post('https://skgo.magio.tv/v2/auth/login',
  File "/srv/system/magiogo-iptv-server/magiogo.py", line 107, in _post
    self._check_response(resp)
  File "/srv/system/magiogo-iptv-server/magiogo.py", line 82, in _check_response
    raise MagioGoException(resp['errorCode'], resp['errorMessage'])
magiogo.MagioGoException: ('Bad Request', 'Nastala chyba. Označenie chyby: jHfTZKd')

**Comment by cvb941** [comment]
Is the git repository up to date (git pull) and without any changes (git reset --hard)?

Other than that, I don't see what the issue could be... Try running the docker container instead, it should provide the same system environment as I have where it is working.

**Comment by Gouster4** [comment]
> Is the git repository up to date (git pull) and without any changes (git reset --hard)?
> 
> Other than that, I don't see what the issue could be... Try running the docker container instead, it should provide the same system environment as I have where it is working.

I did git clone.

And im running it under freebsd without docker support

**Comment by cvb941** [comment]
Okay, the problem is that you have to use `export MAGIO_USERNAME=******` instead of `set MAGIO_USERNAME=*******`, as the latter is applicable for Windows CMD only.

**Comment by Gouster4** [comment]
> Okay, the problem is that you have to use `export MAGIO_USERNAME=******` instead of `set MAGIO_USERNAME=*******`, as the latter is applicable for Windows CMD only.

Thanx a lot. Finally got new error. :D

 * Environment: development
 * Debug mode: on
Stream quality configured to: HIGH (p4)
Logging in to Magio Go TV
Generating .m3u8 playlist
Generating XMLTV guide
 Refreshing finished!
Traceback (most recent call last):
  File "/usr/local/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 995, in main
    cli.main(args=sys.argv[1:])
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 601, in main
    return super().main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 850, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 325, in __init__
    self._load_unlocked()
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 351, in _load_unlocked
    self._app = rv = self.loader()
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 411, in load_app
    app = locate_app(self, import_name, None, raise_if_not_found=False)
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 260, in locate_app
    __import__(module_name)
  File "/srv/system/magiogo-iptv-server/app.py", line 132, in <module>
    scheduler.add_job(refresh, 'interval', hours=int(os.environ.get('MAGIO_GUIDE_REFRESH_HOURS', 12)))
  File "/usr/local/lib/python3.8/site-packages/apscheduler/schedulers/base.py", line 425, in add_job
    'trigger': self._create_trigger(trigger, trigger_args),
  File "/usr/local/lib/python3.8/site-packages/apscheduler/schedulers/base.py", line 926, in _create_trigger
    return self._create_plugin_instance('trigger', trigger, trigger_args)
  File "/usr/local/lib/python3.8/site-packages/apscheduler/schedulers/base.py", line 911, in _create_plugin_instance
    return plugin_cls(**constructor_kwargs)
  File "/usr/local/lib/python3.8/site-packages/apscheduler/triggers/interval.py", line 38, in __init__
    self.timezone = astimezone(timezone)
  File "/usr/local/lib/python3.8/site-packages/apscheduler/util.py", line 96, in astimezone    raise ValueError(
ValueError: Unable to determine the name of the local timezone -- you must explicitly specify the name of the local timezone. Please refrain from using timezones like EST to prevent problems with daylight saving time. Instead, use a locale based timezone name  (such as Europe/Helsinki).  

export TZ=Europe/Bratislava solved that new issue.
Maybe you can mention that export ans timezone in readme.

You can close issue, i dont want to do that until you read it.

**Comment by cvb941** [comment]
Thanks, I will adjust things to make it more clear.
